### ISSUE TITLE
Job "reply_messages (trigger: cron[minute='*/5', second='0'], next run at: 2023-03-19 00:30:00 UTC)" raised an exception Traceback (most recent call last):

### ISSUE THREAD

**Issue by mactitane** [TheExplainthis/ChatGPT-Tinder-Bot#5]
Hello team, i have another error.

Job "reply_messages (trigger: cron[minute='*/5', second='0'], next run at: 2023-03-19 00:30:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/runner/ChatGPT-Tinder-Bot/venv/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/runner/ChatGPT-Tinder-Bot/main.py", line 49, in reply_messages
    response = chatgpt.get_response(content)
  File "/home/runner/ChatGPT-Tinder-Bot/src/chatgpt.py", line 14, in get_response
    response = self.model.chat_completion(messages)
  File "/home/runner/ChatGPT-Tinder-Bot/src/models.py", line 20, in chat_completion
    response = openai.ChatCompletion.create(
  File "/home/runner/ChatGPT-Tinder-Bot/venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/runner/ChatGPT-Tinder-Bot/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/runner/ChatGPT-Tinder-Bot/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/runner/ChatGPT-Tinder-Bot/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/runner/ChatGPT-Tinder-Bot/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid URL (POST /v1/chat/completions)

**Comment by NotSure5655** [comment]
Check ur open ai API again,
It would work.

**Comment by mactitane** [comment]
issue was due to serets variable update. Issue now solved. Thanks a lot !
